spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-mybatis
    username: root
    password: 123456
# 开启驼峰式命名转换，映射关系：user_name-->userName
mybatis:
  configuration:
    map-underscore-to-camel-case: true
